### ISSUE TITLE
Conditionally compiled functions

### ISSUE THREAD

**Issue by ktrianta** [ktrianta/rust-callgraph-benchmark#2]
Conditionally compiled functions might be overlooked by call graph generators.

Add few such examples to make the benchmark more complete.

[More on conditional compilation](https://doc.rust-lang.org/reference/conditional-compilation.html)

**Comment by ktrianta** [comment]
Several examples have been added. It remains to define exactly what the output of a sound call graph generator should be. What about precision of the generated call graph?

**Comment by jhejderup** [comment]
This is a good question w.r.t precision. I believe it could perhaps make sense to add examples exercising such cases (e.g., exactness of resolving Trait-Implementation calls, etc) in the benchmark. Although I am not sure if this is relevant at this stage (or how this can be tested)

**Comment by ktrianta** [comment]
Conditional compilation options are expressed using [Cargo features](https://doc.rust-lang.org/cargo/reference/manifest.html#the-features-section).

A call-graph generator that uses information, which are product of a compilation phase, will be aware only of the the parts of code that were considered relevant according to the activated conditional compilation conditions. This is true because Cargo removes irrelevant to the activated conditions parts of code before invoking the Rust Compiler.

A call-graph generator that would take into account all available code inside conditional compiled sections, would probably achieve that by analysing the program multiple times to cover all possible combinations of activated conditional compilation conditions. Otherwise, it would have to analyse the program once without taking into account conditional compilation conditions, which could result in the program being invalid (duplicate definitions, etc.).

Questions regarding precision should be asked separately from conditional compilation, as it is a more pervasive issue.
